import type { Metadata } from "next";
import { Geist, Geist_Mono, Frank_Ruhl_Libre, Caveat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const frankRuhlLibre = Frank_Ruhl_Libre({
  variable: "--font-frand-ruhl-libre",
  subsets: ["latin"],
  weight: "700",
});

const caveat = Caveat({
  weight: "400",
  variable: "--font-caveat",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${frankRuhlLibre.variable} ${caveat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
